name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  Build:
    if: github.repository == 'CollaborativeStateMachines/cirrina-helm.github.io'
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Perform commit linting
        uses: wagoid/commitlint-github-action@v6